[package]
name = "screader"
version = "0.1.0"
edition = "2021"

[dependencies]
smartcard = "0.3"

[patch.crates-io]
smartcard = { git = "https://github.com/seinlin/smartcard-rs.git", branch = "master" }
